name: patient_app
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.7.2
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.7.2
  flutter_screenutil: ^5.9.3
  image_picker: ^1.2.1
  file_picker: ^10.3.6
  calendar_date_picker2: ^2.0.1
  shared_preferences: ^2.5.3
  google_fonts: ^6.3.2
  url_launcher: ^6.3.2
  clipboard: ^3.0.14
  dio: ^5.9.0
  flutter_inappwebview: ^6.1.5
  intl: ^0.20.2
  permission_handler: ^12.0.1
  agora_rtc_engine: ^6.5.3
  table_calendar: ^3.2.0
  flutter_stripe: ^12.2.0
  stripe_android: ^12.2.0
  stripe_ios: ^12.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/fonts/
    - assets/demo_images/
fonts:
  - family: JakartaSansExtraBold
    fonts:
      - asset: assets/fonts/PlusJakartaSans-ExtraBold.ttf
  - family:    JakartaSansMedium
    fonts:
      - asset: assets/fonts/PlusJakartaSans-Medium.ttf
  - family:    JakartaSansRegular
    fonts:
      - asset: assets/fonts/PlusJakartaSans-Regular.ttf