import 'package:get/get.dart';
import '../utils/app_strings.dart';

class Languages extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
    'en_US': {
      AppStrings.langSupport: "Language Support",
      AppStrings.langDescription: "Ensure accessibility and usability of the application across multiple languages.",
      AppStrings.language: "Language",
      AppStrings.cancel: "Cancel",
      AppStrings.confirm: "Confirm",
      AppStrings.french: "French",
      AppStrings.english: "English",
      AppStrings.basicInfo: "Basic info",
      AppStrings.fullName: "Full Name",
      AppStrings.registrationId: "Registration ID",
      AppStrings.phoneNumber: "Phone Number",
      AppStrings.pharmacyAddress: "Pharmacy Address",
      AppStrings.city: "City",
      AppStrings.areaLocality: "Area / Locality",
      AppStrings.continueText: "Continue",
      AppStrings.completeProfile: "Complete Your Profile",
      AppStrings.dob: "Date of Birth",
      AppStrings.email: "Email",
      AppStrings.gender: "Gender",
      AppStrings.countryResidence: "Country of Residence",
      AppStrings.religion: "Religion",
      AppStrings.department: "Department",
      AppStrings.address: "Address",
      AppStrings.demographicInfo: "Demographic info",
      AppStrings.idNumber: "ID Number",
      AppStrings.clinicAddress: "Clinic Address",
      AppStrings.aboutMe: "About Me",
      AppStrings.aboutMeHint: "Write something about you",
      AppStrings.docsAndReports: "Documents & Reports",
      AppStrings.uploadLabel: "Upload Document/Test Report",
      AppStrings.uploadFormat: "Upload PDF/JPEG",
      AppStrings.tapToSelectNew: "Tap to select a new file",
      AppStrings.submit: "Submit",
      AppStrings.skip: "Skip",
      AppStrings.forgotPassword: "Forgot Password?",
      AppStrings.forgotPasswordSub: "Then Let’s Submit Password Reset.",
      AppStrings.verifyEmail: "Verification via Email",
      AppStrings.verifyEmailSub: "Verify code via email.",
      AppStrings.verifyWhatsapp: "Verification via Whatsapp",
      AppStrings.verifyWhatsappSub: "Verify code via Whatsapp.",
      AppStrings.codeSentEmail: "A 6-digit Code Has Been Sent To Email",
      AppStrings.codeSentWhatsapp: "A 6-digit Code Has Been Sent To Whatsapp",
      AppStrings.medicalVitals: "Medical Vitals",
      AppStrings.height: "Height",
      AppStrings.weight: "Weight",
      AppStrings.bmi: "BMI",
      AppStrings.bloodPressure: "Blood Pressure",
      AppStrings.heartRate: "Heart Rate",
      AppStrings.professionalInfo: "Professional info",
      AppStrings.licenseNumber: "License Number",
      AppStrings.issuingAuthority: "Issuing Authority",
      AppStrings.issueDate: "Issue Date",
      AppStrings.expiryDate: "Expiry Date",
      AppStrings.businessRegNo: "Business Reg. No.",
      AppStrings.registeredName: "Registered Name",
      AppStrings.uploadInstruction: "Upload valid, clear documents for verification. Only PDF/JPEG are accepted.",
      AppStrings.licenseCertificate: "License Certificate",
      AppStrings.uploadLicense: "Upload your License Certificate",
      AppStrings.acceptedFilesInfo: "Accepted files: PDF, JPEG – max 5MB.",
      AppStrings.taxClearance: "Tax Clearance",
      AppStrings.uploadTax: "Upload Tax Clearance",
      AppStrings.nocCertificate: "Noc Certificate",
      AppStrings.uploadNoc: "Upload your Noc Certificate",
      AppStrings.payment: "Payment",
      AppStrings.bankVerificationLetter: "Bank Verification Letter",
      AppStrings.uploadBankConfirmation: "Upload bank confirmation",
      AppStrings.paymentAuthorization: "Payment Authorization",
      AppStrings.attachSignedForm: "Attach signed form",
      AppStrings.nationalIdDoc: "National Identity Document",
      AppStrings.medicalSpeciality: "Medical Speciality",
      AppStrings.experienceYears: "Experience (in years)",
      AppStrings.fee: "Fee",
      AppStrings.dateOfRegistration: "Date of Registration",
      AppStrings.placeOfPractice: "Place of Practice",
      AppStrings.year: "Year",
      AppStrings.resetPassword: "Reset Password",
      AppStrings.resetPasswordSub: "Access Your Secure Medical Account",
      AppStrings.newPassword: "New Password",
      AppStrings.enterPasswordHint: "Enter your password",
      AppStrings.confirmPassword: "Confirm Password",
      AppStrings.reviewAndSubmission: "Review & Submission",
      AppStrings.personalInfo: "Personal Info",
      AppStrings.supportingDocuments: "Supporting Documents",
      AppStrings.consentDataProcessing: "I consent to the processing of my personal data",
      AppStrings.submissionConsentDetails: "By submitting, you consent to the processing of your data for professional verification purposes. Your information is securely handled under GDPR and HDS standards.",
      AppStrings.submitForVerification: "Submit for Verification",
      AppStrings.signIn: "Sign In",
      AppStrings.password: "Password",
      AppStrings.forgetPasswordTitle: "Forget Password",
      AppStrings.dontHaveAccount: "Don't have an account?",
      AppStrings.signUp: "Sign Up",
      AppStrings.createAccountSub: "Create your secure medical account",
      AppStrings.iAmDoctor: "You are a doctor",
      AppStrings.iAmPatient: "You are a patient",
      AppStrings.iAmPharmacist: "You are a pharmacist",
      AppStrings.alreadyHaveAccount: "Already have an account?",
      AppStrings.identityDocuments: "Identity Documents",
      AppStrings.uploadDocument: "Upload your Document",
      AppStrings.passportIdFront: "Passport or ID Front",
      AppStrings.uploadFrontSide: "Upload front side",
      AppStrings.credentials: "Credentials",
      AppStrings.medicalLicense: "Medical License",
      AppStrings.uploadValidLicense: "Upload your valid license",
      AppStrings.diplomaCertification: "Diploma / Certification",
      AppStrings.uploadDiplomaTranscript: "Upload diploma or transcript",
      AppStrings.legal: "Legal",
      AppStrings.liabilityInsuranceProof: "Liability Insurance Proof",
      AppStrings.uploadInsuranceDoc: "Upload insurance document",
      AppStrings.cnpdGdprForm: "CNPD / GDPR Form",
      AppStrings.attachComplianceForm: "Attach compliance form",
      AppStrings.twoFactorAuth: "Two-Factor\n Authentication",
      AppStrings.twoFactorSub: "Then Let’s Submit Password Reset.",
      AppStrings.verifyViaEmail: "Verification via Email",
      AppStrings.emailCodeSent: "A 6-digit Code Has Been Sent To Email",
      AppStrings.verifyViaWhatsapp: "Verification via Whatsapp",
      AppStrings.whatsappCodeSent: "A 6-digit Code Has Been Sent To Whatsapp",
      AppStrings.back: "Back",
      AppStrings.verification: "Verification",
      AppStrings.requestNewCode: "You can request a new code now.",
      AppStrings.codeExpiresSoon: "Code expires soon.",
      AppStrings.resendToWhatsapp: "Re-send To Whatsapp",
      AppStrings.incompleteCode: "Incomplete Code",
      AppStrings.incompleteCodeMsg: "Please enter the complete 6-digit verification code.",

    },
    'fr_FR': {
      AppStrings.langSupport: "Support Linguistique",
      AppStrings.langDescription: "Assurer l'accessibilité et la convivialité de l'application dans plusieurs langues.",
      AppStrings.language: "Langue",
      AppStrings.cancel: "Annuler",
      AppStrings.confirm: "Confirmer",
      AppStrings.french: "Français",
      AppStrings.english: "Anglais",
      AppStrings.basicInfo: "Informations de base",
      AppStrings.fullName: "Nom complet",
      AppStrings.registrationId: "ID d'enregistrement",
      AppStrings.phoneNumber: "Numéro de téléphone",
      AppStrings.pharmacyAddress: "Adresse de la pharmacie",
      AppStrings.city: "Ville",
      AppStrings.areaLocality: "Zone / Localité",
      AppStrings.continueText: "Continuer",
      AppStrings.completeProfile: "Complétez votre profil",
      AppStrings.dob: "Date de naissance",
      AppStrings.email: "E-mail",
      AppStrings.gender: "Genre",
      AppStrings.countryResidence: "Pays de résidence",
      AppStrings.religion: "Religion",
      AppStrings.department: "Département",
      AppStrings.address: "Adresse",
      AppStrings.demographicInfo: "Informations démographiques",
      AppStrings.idNumber: "Numéro d'identification",
      AppStrings.clinicAddress: "Adresse de la clinique",
      AppStrings.aboutMe: "À propos de moi",
      AppStrings.aboutMeHint: "Écrivez quelque chose sur vous",
      AppStrings.docsAndReports: "Documents et rapports",
      AppStrings.uploadLabel: "Télécharger un document/rapport de test",
      AppStrings.uploadFormat: "Télécharger PDF/JPEG",
      AppStrings.tapToSelectNew: "Appuyez pour sélectionner un nouveau fichier",
      AppStrings.submit: "Soumettre",
      AppStrings.skip: "Passer",
      AppStrings.forgotPassword: "Mot de passe oublié ?",
      AppStrings.forgotPasswordSub: "Ensuite, soumettons la réinitialisation du mot de passe.",
      AppStrings.verifyEmail: "Vérification par e-mail",
      AppStrings.verifyEmailSub: "Vérifier le code par e-mail.",
      AppStrings.verifyWhatsapp: "Vérification via Whatsapp",
      AppStrings.verifyWhatsappSub: "Vérifier le code via Whatsapp.",
      AppStrings.codeSentEmail: "Un code à 6 chiffres a été envoyé par e-mail",
      AppStrings.codeSentWhatsapp: "Un code à 6 chiffres a été envoyé sur Whatsapp",
      AppStrings.medicalVitals: "Signes Vitaux",
      AppStrings.height: "Taille",
      AppStrings.weight: "Poids",
      AppStrings.bmi: "IMC",
      AppStrings.bloodPressure: "Tension Artérielle",
      AppStrings.heartRate: "Fréquence Cardiaque",
      AppStrings.professionalInfo: "Informations professionnelles",
      AppStrings.licenseNumber: "Numéro de licence",
      AppStrings.issuingAuthority: "Autorité de délivrance",
      AppStrings.issueDate: "Date d'émission",
      AppStrings.expiryDate: "Date d'expiration",
      AppStrings.businessRegNo: "N° d'enregistrement de l'entreprise",
      AppStrings.registeredName: "Nom enregistré",
      AppStrings.uploadInstruction: "Téléchargez des documents valides et clairs pour vérification. Seuls les formats PDF/JPEG sont acceptés.",
      AppStrings.licenseCertificate: "Certificat de licence",
      AppStrings.uploadLicense: "Téléchargez votre certificat de licence",
      AppStrings.acceptedFilesInfo: "Fichiers acceptés : PDF, JPEG – max 5 Mo.",
      AppStrings.taxClearance: "Quittance fiscale",
      AppStrings.uploadTax: "Télécharger la quittance fiscale",
      AppStrings.nocCertificate: "Certificat NOC",
      AppStrings.uploadNoc: "Téléchargez votre certificat NOC",
      AppStrings.payment: "Paiement",
      AppStrings.bankVerificationLetter: "Lettre de vérification bancaire",
      AppStrings.uploadBankConfirmation: "Télécharger la confirmation bancaire",
      AppStrings.paymentAuthorization: "Autorisation de paiement",
      AppStrings.attachSignedForm: "Joindre le formulaire signé",
      AppStrings.nationalIdDoc: "Document d'identité national",
      AppStrings.medicalSpeciality: "Spécialité médicale",
      AppStrings.experienceYears: "Expérience (en années)",
      AppStrings.fee: "Honoraires",
      AppStrings.dateOfRegistration: "Date d'enregistrement",
      AppStrings.placeOfPractice: "Lieu d'exercice",
      AppStrings.year: "Année",
      AppStrings.resetPassword: "Réinitialiser le mot de passe",
      AppStrings.resetPasswordSub: "Accédez à votre compte médical sécurisé",
      AppStrings.newPassword: "Nouveau mot de passe",
      AppStrings.enterPasswordHint: "Entrez votre mot de passe",
      AppStrings.confirmPassword: "Confirmez le mot de passe",
      AppStrings.reviewAndSubmission: "Révision et soumission",
      AppStrings.personalInfo: "Informations personnelles",
      AppStrings.supportingDocuments: "Documents justificatifs",
      AppStrings.consentDataProcessing: "Je consens au traitement de mes données personnelles",
      AppStrings.submissionConsentDetails: "En soumettant, vous consentez au traitement de vos données à des fins de vérification professionnelle. Vos informations sont traitées en toute sécurité selon les normes RGPD et HDS.",
      AppStrings.submitForVerification: "Soumettre pour vérification",
      AppStrings.signIn: "Se connecter",
      AppStrings.password: "Mot de passe",
      AppStrings.forgetPasswordTitle: "Mot de passe oublié",
      AppStrings.dontHaveAccount: "Vous n'avez pas de compte ?",
      AppStrings.signUp: "S'inscrire",
      AppStrings.createAccountSub: "Créez votre compte médical sécurisé",
      AppStrings.iAmDoctor: "Vous êtes médecin",
      AppStrings.iAmPatient: "Vous êtes un patient",
      AppStrings.iAmPharmacist: "Vous êtes pharmacien",
      AppStrings.alreadyHaveAccount: "Vous avez déjà un compte ?",
      AppStrings.identityDocuments: "Documents d'identité",
      AppStrings.uploadDocument: "Téléchargez votre document",
      AppStrings.passportIdFront: "Passeport ou recto de la carte d'identité",
      AppStrings.uploadFrontSide: "Télécharger le recto",
      AppStrings.credentials: "Références",
      AppStrings.medicalLicense: "Licence médicale",
      AppStrings.uploadValidLicense: "Téléchargez votre licence valide",
      AppStrings.diplomaCertification: "Diplôme / Certification",
      AppStrings.uploadDiplomaTranscript: "Télécharger le diplôme ou le relevé de notes",
      AppStrings.legal: "Juridique",
      AppStrings.liabilityInsuranceProof: "Preuve d'assurance responsabilité civile",
      AppStrings.uploadInsuranceDoc: "Télécharger le document d'assurance",
      AppStrings.cnpdGdprForm: "Formulaire CNPD / RGPD",
      AppStrings.attachComplianceForm: "Joindre le formulaire de conformité",
      AppStrings.twoFactorAuth: "Authentification à\n deux facteurs",
      AppStrings.twoFactorSub: "Ensuite, soumettons la réinitialisation du mot de passe.",
      AppStrings.verifyViaEmail: "Vérification par e-mail",
      AppStrings.emailCodeSent: "Un code à 6 chiffres a été envoyé par e-mail",
      AppStrings.verifyViaWhatsapp: "Vérification via Whatsapp",
      AppStrings.whatsappCodeSent: "Un code à 6 chiffres a été envoyé sur Whatsapp",
      AppStrings.back: "Retour",
      AppStrings.verification: "Vérification",
      AppStrings.requestNewCode: "Vous pouvez demander un nouveau code maintenant.",
      AppStrings.codeExpiresSoon: "Le code expire bientôt.",
      AppStrings.resendToWhatsapp: "Renvoyer sur Whatsapp",
      AppStrings.incompleteCode: "Code incomplet",
      AppStrings.incompleteCodeMsg: "Veuillez saisir le code de vérification complet à 6 chiffres.",
    },
  };
}