import 'package:get/get.dart';
import '../utils/app_strings.dart';

class Languages extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
    'en_US': {
      AppStrings.langSupport: "Language Support",
      AppStrings.langDescription: "Ensure accessibility and usability of the application across multiple languages.",
      AppStrings.language: "Language",
      AppStrings.cancel: "Cancel",
      AppStrings.confirm: "Confirm",
      AppStrings.french: "French",
      AppStrings.english: "English",
      AppStrings.basicInfo: "Basic info",
      AppStrings.fullName: "Full Name",
      AppStrings.registrationId: "Registration ID",
      AppStrings.phoneNumber: "Phone Number",
      AppStrings.pharmacyAddress: "Pharmacy Address",
      AppStrings.city: "City",
      AppStrings.areaLocality: "Area / Locality",
      AppStrings.continueText: "Continue",
      AppStrings.completeProfile: "Complete Your Profile",
      AppStrings.dob: "Date of Birth",
      AppStrings.email: "Email",
      AppStrings.gender: "Gender",
      AppStrings.countryResidence: "Country of Residence",
      AppStrings.religion: "Religion",
      AppStrings.department: "Department",
      AppStrings.address: "Address",
      AppStrings.demographicInfo: "Demographic info",
      AppStrings.idNumber: "ID Number",
      AppStrings.clinicAddress: "Clinic Address",
      AppStrings.aboutMe: "About Me",
      AppStrings.aboutMeHint: "Write something about you",
      AppStrings.docsAndReports: "Documents & Reports",
      AppStrings.uploadLabel: "Upload Document/Test Report",
      AppStrings.uploadFormat: "Upload PDF/JPEG",
      AppStrings.tapToSelectNew: "Tap to select a new file",
      AppStrings.submit: "Submit",
      AppStrings.skip: "Skip",
      AppStrings.forgotPassword: "Forgot Password?",
      AppStrings.forgotPasswordSub: "Then Let’s Submit Password Reset.",
      AppStrings.verifyEmail: "Verification via Email",
      AppStrings.verifyEmailSub: "Verify code via email.",
      AppStrings.verifyWhatsapp: "Verification via Whatsapp",
      AppStrings.verifyWhatsappSub: "Verify code via Whatsapp.",
      AppStrings.codeSentEmail: "A 6-digit Code Has Been Sent To Email",
      AppStrings.codeSentWhatsapp: "A 6-digit Code Has Been Sent To Whatsapp",
      AppStrings.medicalVitals: "Medical Vitals",
      AppStrings.height: "Height",
      AppStrings.weight: "Weight",
      AppStrings.bmi: "BMI",
      AppStrings.bloodPressure: "Blood Pressure",
      AppStrings.heartRate: "Heart Rate",
      AppStrings.professionalInfo: "Professional info",
      AppStrings.licenseNumber: "License Number",
      AppStrings.issuingAuthority: "Issuing Authority",
      AppStrings.issueDate: "Issue Date",
      AppStrings.expiryDate: "Expiry Date",
      AppStrings.businessRegNo: "Business Reg. No.",
      AppStrings.registeredName: "Registered Name",
      AppStrings.uploadInstruction: "Upload valid, clear documents for verification. Only PDF/JPEG are accepted.",
      AppStrings.licenseCertificate: "License Certificate",
      AppStrings.uploadLicense: "Upload your License Certificate",
      AppStrings.acceptedFilesInfo: "Accepted files: PDF, JPEG – max 5MB.",
      AppStrings.taxClearance: "Tax Clearance",
      AppStrings.uploadTax: "Upload Tax Clearance",
      AppStrings.nocCertificate: "Noc Certificate",
      AppStrings.uploadNoc: "Upload your Noc Certificate",
      AppStrings.payment: "Payment",
      AppStrings.bankVerificationLetter: "Bank Verification Letter",
      AppStrings.uploadBankConfirmation: "Upload bank confirmation",
      AppStrings.paymentAuthorization: "Payment Authorization",
      AppStrings.attachSignedForm: "Attach signed form",
      AppStrings.nationalIdDoc: "National Identity Document",
      AppStrings.medicalSpeciality: "Medical Speciality",
      AppStrings.experienceYears: "Experience (in years)",
      AppStrings.fee: "Fee",
      AppStrings.dateOfRegistration: "Date of Registration",
      AppStrings.placeOfPractice: "Place of Practice",
      AppStrings.year: "Year",
      AppStrings.resetPassword: "Reset Password",
      AppStrings.resetPasswordSub: "Access Your Secure Medical Account",
      AppStrings.newPassword: "New Password",
      AppStrings.enterPasswordHint: "Enter your password",
      AppStrings.confirmPassword: "Confirm Password",
      AppStrings.reviewAndSubmission: "Review & Submission",
      AppStrings.personalInfo: "Personal Info",
      AppStrings.supportingDocuments: "Supporting Documents",
      AppStrings.consentDataProcessing: "I consent to the processing of my personal data",
      AppStrings.submissionConsentDetails: "By submitting, you consent to the processing of your data for professional verification purposes. Your information is securely handled under GDPR and HDS standards.",
      AppStrings.submitForVerification: "Submit for Verification",
      AppStrings.signIn: "Sign In",
      AppStrings.password: "Password",
      AppStrings.forgetPasswordTitle: "Forget Password",
      AppStrings.dontHaveAccount: "Don't have an account?",
      AppStrings.signUp: "Sign Up",
      AppStrings.createAccountSub: "Create your secure medical account",
      AppStrings.iAmDoctor: "You are a doctor",
      AppStrings.iAmPatient: "You are a patient",
      AppStrings.iAmPharmacist: "You are a pharmacist",
      AppStrings.alreadyHaveAccount: "Already have an account?",
      AppStrings.identityDocuments: "Identity Documents",
      AppStrings.uploadDocument: "Upload your Document",
      AppStrings.passportIdFront: "Passport or ID Front",
      AppStrings.uploadFrontSide: "Upload front side",
      AppStrings.credentials: "Credentials",
      AppStrings.medicalLicense: "Medical License",
      AppStrings.uploadValidLicense: "Upload your valid license",
      AppStrings.diplomaCertification: "Diploma / Certification",
      AppStrings.uploadDiplomaTranscript: "Upload diploma or transcript",
      AppStrings.legal: "Legal",
      AppStrings.liabilityInsuranceProof: "Liability Insurance Proof",
      AppStrings.uploadInsuranceDoc: "Upload insurance document",
      AppStrings.cnpdGdprForm: "CNPD / GDPR Form",
      AppStrings.attachComplianceForm: "Attach compliance form",
      AppStrings.twoFactorAuth: "Two-Factor\n Authentication",
      AppStrings.twoFactorSub: "Then Let’s Submit Password Reset.",
      AppStrings.verifyViaEmail: "Verification via Email",
      AppStrings.emailCodeSent: "A 6-digit Code Has Been Sent To Email",
      AppStrings.verifyViaWhatsapp: "Verification via Whatsapp",
      AppStrings.whatsappCodeSent: "A 6-digit Code Has Been Sent To Whatsapp",
      AppStrings.back: "Back",
      AppStrings.verification: "Verification",
      AppStrings.requestNewCode: "You can request a new code now.",
      AppStrings.codeExpiresSoon: "Code expires soon.",
      AppStrings.resendToWhatsapp: "Re-send To Whatsapp",
      AppStrings.incompleteCode: "Incomplete Code",
      AppStrings.incompleteCodeMsg: "Please enter the complete 6-digit verification code.",
      AppStrings.hello: "Hello,",
      AppStrings.tomorrowAt: "Tomorrow at",
      AppStrings.ongoingAppointment: "Ongoing Appointment",
      AppStrings.upcomingAppointment: "Upcoming Appointment",
      AppStrings.appointments: "Appointments",
      AppStrings.prescription: "Prescription",
      AppStrings.orders: "Orders",
      AppStrings.heartSurgeon: "Heart Surgeon",
      AppStrings.gastroenterologist: "Gastroenterologist",
      AppStrings.remoteConsultation: "Remote Consultation",
      AppStrings.join: "Join",
      AppStrings.sunday: "Sunday",
      AppStrings.june: "June",AppStrings.currentOrder: "Current Order",
      AppStrings.trackOrder: "Track Order",
      AppStrings.detail: "Detail",
      AppStrings.packageId: "Package ID",
      AppStrings.from: "From",
      AppStrings.estimated: "Estimated",
      AppStrings.mint: "mint",
      AppStrings.orderStep: "Order",
      AppStrings.preparingStep: "Preparing",
      AppStrings.inDeliveryStep: "In Delivery",
      AppStrings.deliveredStep: "Delivered",
      AppStrings.nextActions: "Next Actions",
      AppStrings.uploadPrescription: "Upload Prescription",
      AppStrings.dosage: "Dosage",
      AppStrings.morningEvening: "Morning/Evening",
      AppStrings.refill: "Refill",
      AppStrings.notifications: "Notifications",
      AppStrings.newCount: "New",
      AppStrings.markAllRead: "Mark all as read",
      AppStrings.today: "Today",
      AppStrings.yesterday: "Yesterday",
      AppStrings.chat: "Chat",
      AppStrings.search: "Search",
      AppStrings.chatDescription: "Communicate here with your practitioner for any questions regarding your treatment or tests",
      AppStrings.noDataFound: "No Data Found",
      AppStrings.online: "Online",
      AppStrings.typeAMessage: "Message",
      AppStrings.searchHint: "Search",
      AppStrings.findDoctorSub: "Let’s find a suitable doctor for you",
      AppStrings.doctorsFound: "doctors found",
      AppStrings.date: "Date",
      AppStrings.selectDate: "Select Date",
      AppStrings.location: "Location",
      AppStrings.consultationMode: "Consultation Mode",
      AppStrings.inPerson: "In-Person",
      AppStrings.teleconsultation: "Teleconsultation",
      AppStrings.distance: "Distance",
      AppStrings.male: "Male",
      AppStrings.female: "Female",
      AppStrings.price: "Price",
      AppStrings.reset: "Reset",
      AppStrings.apply: "Apply",
      AppStrings.profile: "Profile",
      AppStrings.profileSub: "Real-Time Messaging For Consultations.",
      AppStrings.documentsAndReports: "Documents & Reports",
      AppStrings.deleteAccount: "Delete Account",
      AppStrings.lastUpdate: "Last update",
      AppStrings.editPersonalInfo: "Edit Personal Info",
      AppStrings.patientId: "Patient ID",
      AppStrings.countryOfResidence: "Country of Residence",
      AppStrings.phone: "Phone",
      AppStrings.healthSpace: "Health Space",
      AppStrings.allergies: "Allergies",
      AppStrings.medicalHistory: "Medical History",
      AppStrings.updatePassword: "Update Password",
      AppStrings.bloodType: "Blood Type",
      AppStrings.privacySecurity: "Privacy & Security",
      AppStrings.changeLanguage: "Change Language",
      AppStrings.consultationPlan: "Consultation Plan",
      AppStrings.logOut: "Log Out",
      AppStrings.editMedicalVitals: "Edit Medical Vitals",
      AppStrings.uploadNow: "Upload now",
      AppStrings.viewing: "Viewing",
      AppStrings.deleting: "Deleting",
      AppStrings.action: "Action",
      AppStrings.helpCenter: "Help Center",
      AppStrings.faqs: "FAQ'S",
      AppStrings.faqQuestion1: "1. Are certificates internationally recognized?",
      AppStrings.faqQuestion2: "2. Do I need to renew my membership manually?",
      AppStrings.faqQuestion3: "3. Do I get CME credits with all plans?",
      AppStrings.emailAddress: "Email Address",
      AppStrings.update: "Update",
      AppStrings.addAllergy: "Add Allergy",
      AppStrings.medical: "Medical",
      AppStrings.allergenName: "Allergen name",
      AppStrings.penicillin: "Penicillin",
      AppStrings.reaction: "Reaction",
      AppStrings.rash: "Rash",
      AppStrings.severity: "Severity",
      AppStrings.dateIdentified: "Date Identified",
      AppStrings.note: "Note",
      AppStrings.writeNoteHint: "Write a note to your doctor",
      AppStrings.save: "Save",
      AppStrings.currentMedication: "Current Medication",
      AppStrings.vaccinationHistory: "Vaccination History",
      AppStrings.familyHistory: "Family History",
      AppStrings.lifestyle: "Lifestyle",
      AppStrings.addMedication: "Add Medication",
      AppStrings.addVaccinationHistory: "Add Vaccination History",
      AppStrings.addFamilyHistory: "Add Family History",
      AppStrings.addLifeStyle: "Add Life Style",
      AppStrings.oldPassword: "Old Password",
      AppStrings.atLeast8Chars: "At least 8 characters",
      AppStrings.atLeastOneUpper: "At least one uppercase letter E.g: X,Y,Z",
      AppStrings.atLeastOneNumber: "At least one number E.g: 1,2,3",
      AppStrings.atLeastOneSpecial: "At least one special character E.g: @,!, \$",
      AppStrings.passwordNotMatch: "Passwords do not match.",
      AppStrings.currentBloodType: "Current Blood Type",
      AppStrings.lastConfirmed: "Last confirmed",
      AppStrings.source: "Source",
      AppStrings.verificationStatus: "Verification status",
      AppStrings.jan2024: "Jan 2024",
      AppStrings.medicalTestReport: "Medical Test Report",
      AppStrings.verified: "Verified",
      AppStrings.updateBloodType: "Update Blood Type",
      AppStrings.editBloodType: "Edit Blood Type",
      AppStrings.uploadTestProof: "Upload test proof",
      AppStrings.uploadProofOptional: "Upload test proof (optional)",
      AppStrings.dataSharingPrefs: "Data Sharing Preferences",
      AppStrings.dataSharingControl: "Control How Your Medical Data Is Shared And Used",
      AppStrings.dataProtected: "Your Data is Protected",
      AppStrings.allowSharingHealthcare: "Allow Data Sharing With Other Healthcare Professionals",
      AppStrings.allowSharingSubtitle: "Enable to share medical history for coordinated care",
      AppStrings.allowResearchData: "Allow Anonymized Data For Research",
      AppStrings.allowResearchSubtitle: "Used only for aggregated medical insights",
      AppStrings.receiveDataNotifications: "Receive Data-Related Notifications",
      AppStrings.receiveNotificationsSubtitle: "Get alerts when your data is accessed or shared",
      AppStrings.whoCanAccessData: "Who Can Access My Data?",
      AppStrings.specialist: "Specialists",
      AppStrings.specialistSubtitle: "Can view upon your authorization",
      AppStrings.emergencyServices: "Emergency Services",
      AppStrings.emergencySubtitle: "Temporary 30-day access possible",
      AppStrings.pharmacy: "Pharmacy",
      AppStrings.pharmacySubtitle: "Only for prescriptions or test uploads",
      AppStrings.alwaysAccessDefault: "Always has access by default",
      AppStrings.accessHistory: "Access History",
      AppStrings.trackHistorySubtitle: "Track Who Viewed Or Modified Your Records",
      AppStrings.name: "Name",
      AppStrings.role: "Role",
      AppStrings.data: "Data",
      AppStrings.dateTime: "Date & Time",
      AppStrings.exportMyData: "Export My Data",
      AppStrings.pdf: "PDF",
      AppStrings.selectDataType: "Select data type",
      AppStrings.dataController: "Data Controller",
      AppStrings.dpoContact: "DPO Contact",
      AppStrings.hosting: "Hosting:",
      AppStrings.gdprCompliance: "All operations comply with GDPR, CNPD, and HDS standards.",
      AppStrings.myConsultationPlans: "My Consultation Plans",
      AppStrings.activePlan: "Active Plan(2)",
      AppStrings.planHistory: "Plan History",
      AppStrings.searchConsultationHint: "Search by date,status...",
      AppStrings.noOrdersFound: "No orders found.",
      AppStrings.consultationPlanDetail: "Consultation Plan Detail",
      AppStrings.planInfo: "Plan Info",
      AppStrings.renewPlan: "Renew Plan",
      AppStrings.downloadInvoice: "Download Invoice",
      AppStrings.premiumTelePlan: "Premium Tele-Consultation\nPlan",
      AppStrings.active: "Active",
      AppStrings.videoConsultation: "Video Consultation",
      AppStrings.expiresOn: "Expires on",
      AppStrings.durationDays: "Duration: @days days",
      AppStrings.credits: "@count credits",
      AppStrings.description: "Description",
      AppStrings.planDescriptionText: "Symptoms improving, headache frequency reduced from 5 to 2 times per week. Advised patient to continue current regimen and maintain sleep hygiene",
      AppStrings.usageLog: "Usage Log",
      AppStrings.usageLogSubtitle: "Track Who Viewed Or Modified Your Records",
      AppStrings.consultationDate: "Consultation Date",
      AppStrings.type: "Type",
      AppStrings.doctor: "Doctor",
      AppStrings.status: "Status",
      AppStrings.completed: "COMPLETED",
      AppStrings.missed: "Missed",
      AppStrings.deleteAccountWarning: "This action will permanently delete your medical data and profile, in accordance with GDPR",
      AppStrings.autoDataDownload: "Automatic data download before deletion",
      AppStrings.relationLabel: "Relation @relation",
      AppStrings.diabetes: "Diabetes",
      AppStrings.ageLabel: "Age: @age year",
      AppStrings.severityLabel: "Severity: @severity",
      AppStrings.mild: "Mild",
      AppStrings.antibioticWarning: "Avoid antibiotics in same family",
      AppStrings.lastUpdated: "Last updated: @date",
      AppStrings.editAllergy: "Edit Allergy",
      AppStrings.allergyStatus: "Allergy Status",
      AppStrings.uploadDocPhoto: "Upload Document/Photo",
      AppStrings.uploadPdfJpeg: "Upload PDF/JPEG",
      AppStrings.tapToSelectNewFile: "Tap to select a new file",
      AppStrings.noFileSelected: "No file selected",
      AppStrings.selectionCancelled: "File selection cancelled",
      AppStrings.writeNoteToDoctor: "Write a note to your doctor",
      AppStrings.addVaccination: "Add Vaccination",
      AppStrings.vaccinationName: "Vaccination Name",
      AppStrings.influenza: "Influenza",
      AppStrings.uploadCertificate: "Upload Certificate",
      AppStrings.uploadLabReportHint: "Upload lab test or report (PDF, JPG, PNG)",
      AppStrings.addAndSave: "Add & Save",
      AppStrings.medicationName: "Medication Name",
      AppStrings.metforminHint: "Metformin 500mg",
      AppStrings.dosageHint: "1 tablet twice daily",
      AppStrings.doctorHint: "Dr. Maria Waston",
      AppStrings.addLifestyle: "Add LifeStyle",
      AppStrings.smoking: "Smoking",
      AppStrings.alcohol: "Alcohol",
      AppStrings.diet: "Diet",
      AppStrings.physicalActivity: "Physical Activity",
      AppStrings.relation: "Relation",
      AppStrings.condition: "Condition",
      AppStrings.hypertension: "Hypertension",
      AppStrings.age: "Age",
      AppStrings.ageHint: "20",
      AppStrings.consultationFinished: "Consultation Finished",
      AppStrings.thankYouDoctor: "Thank You For Visiting @name",
      AppStrings.visitRatingTitle: "How would you rate this\nvisit?",
      AppStrings.feedbackHint: "Tell us about your experience......",
      AppStrings.viewPrescription: "View Prescription",
      AppStrings.send: "Send",
      AppStrings.preview: "Preview",
      AppStrings.encryptedCallNote: "End-to-end encrypted call.",
      AppStrings.launchVideo: "Launch Video",
      AppStrings.settings: "Settings",
      AppStrings.lastTested: "Last tested: @time",
      AppStrings.minutesAgo: "Minutes ago",
      AppStrings.saveSettings: "Save Settings",
      AppStrings.restoreDefaults: "Restore Defaults",
      AppStrings.doctorNotes: "Doctor Notes",
      AppStrings.addPrescription: "Add Prescription",
      AppStrings.recentProjects: "Recent Projects",
      AppStrings.endCall: "End Call",
      AppStrings.end: "End",
      AppStrings.inVideoMessages: "In-video messages",
      AppStrings.share: "Share",
      AppStrings.captionsOff: "Captions off",
      AppStrings.addDoctorNote: "Add Doctor Note",
      AppStrings.addPrescriptionMenu: "Add Prescription",
      AppStrings.viewReports: "View Reports",
      AppStrings.patientHistory: "Patient History",
      AppStrings.observationsSubtitle: "Record Key Observations During This Consultation",
      AppStrings.addNote: "Add Note",
      AppStrings.noteHint: "Write observations during the consultation",
      AppStrings.noteSave: "Note Save",
      AppStrings.patientName: "Patient Name",
      AppStrings.patientNameHint: "Mr John",
      AppStrings.medicines: "Medicines",
      AppStrings.medicinesHint: "Enter Medicines",
      AppStrings.refillDate: "Refill Date",
      AppStrings.dateHint: "Enter date",
      AppStrings.prescriptionNotesHint: "Avoid antibiotics in same family",
      AppStrings.sendToPatient: "Send to Patient",
      AppStrings.uploadNewReport: "Upload New Report",
      AppStrings.bloodTest: "Blood Test",
      AppStrings.chestXray: "Chest X-ray",
      AppStrings.jan2025: "Jan 2025",
      AppStrings.endingCall: "Ending Call",
      AppStrings.endCallForBoth: "End call for both participants?",
      AppStrings.anonymousFeedbackNote: "Your feedback is anonymous and helps improve service quality",
      AppStrings.addNewCard: "Add New Card",
      AppStrings.cardHolderName: "Card Holder Name",
      AppStrings.enterName: "Enter Name",
      AppStrings.cardNumber: "Card Number",
      AppStrings.saveDetail: "Save Detail",
      AppStrings.bookAppointment: "Book Appointment",
      AppStrings.section: "Section",
      AppStrings.details: "Details",
      AppStrings.confirmation: "Confirmation",
      AppStrings.remote: "Remote",
      AppStrings.homeVisit: "Home Visit",
      AppStrings.availableTimes: "Available Times",
      AppStrings.homeVisitAlert: "This service is only available for practitioners\noffering home visits.",
      AppStrings.confirmAppointment: "Confirm Appointment",
      AppStrings.submitRequest: "Submit Request",
      AppStrings.cardHolderLabel: "CARD HOLDER",
      AppStrings.myAppointment: "My Appointment",
      AppStrings.consultationDuration: "1 Hour Consultation",
      AppStrings.appointmentSummary: "Appointment Summary",
      AppStrings.next: "Next",
      AppStrings.doctorDetails: "Doctor Details",
      AppStrings.showNumber: "Show Number",
      AppStrings.patients: "patients",
      AppStrings.experience: "experience",
      AppStrings.rating: "rating",
      AppStrings.reviews: "reviews",
      AppStrings.years: "years",
      AppStrings.orderSummary: "Summary",
      AppStrings.priceFor: "Price for",
      AppStrings.deliveryCharges: "Delivery Charges",
      AppStrings.homeDeliveryNote: "if home delivery",
      AppStrings.totalFee: "Total Fee",
      AppStrings.estimatedDeliveryTime: "Estimated Delivery Time",
      AppStrings.expectedDeliveryDays: "Expected within 2–3 business days",
      AppStrings.certificationNote: "Licensed Pharmacy — Certified by CNPD & Ministry of Health",
      AppStrings.confirmOrder: "Confirm order",
      AppStrings.prescriptionReceived: "Prescription Received",
      AppStrings.prescriptionAvailableNote: "Your Prescription Is Available",
      AppStrings.modify: "Modify",
      AppStrings.prescriptionDetails: "Prescription Details",
      AppStrings.expirySoon: "Expiry Soon",
      AppStrings.expired: "Expired",
      AppStrings.prescriptionInfo: "Prescription Info",
      AppStrings.dateOfIssue: "Date of issue",
      AppStrings.validUntil: "Valid Until",
      AppStrings.eligibleTill: "Eligible Till:",
      AppStrings.nextDays: "Next @days days",
      AppStrings.diagnosisHistory: "Diagnosis History",
      AppStrings.diagnosis: "Diagnosis",
      AppStrings.notes: "Notes",
      AppStrings.prescriptionHistory: "Prescription History",
      AppStrings.prescriptions: "Prescriptions",
      AppStrings.privacyNote: "Encrypted & compliant with GDPR/HDS",
      AppStrings.electronicSign: "Electronic Sign",
      AppStrings.digitalSignNote: "This digital prescription is generated and signed by a verified practitioner",
      AppStrings.getMedicine: "Get Medicine",
      AppStrings.downloadPdf: "Download PDF",
      AppStrings.encryptionNote: "Encrypted & compliant with GDPR/HDS",
      AppStrings.activePrescriptions: "Active Prescriptions",
      AppStrings.pastPrescriptions: "Past Prescriptions",
      AppStrings.refillStatus: "Refill Status",
      AppStrings.approved: "Approved",
      AppStrings.noteLabel: "Note",
      AppStrings.noNotesAvailable: "No notes Available",
      AppStrings.orderMedicine: "Order Medicine",
      AppStrings.requestRefill: "Request Refill",
      AppStrings.refillCycles: "Refill cycles",
      AppStrings.refillLabel: "Refill",
      AppStrings.sendRequest: "Send Request",
      AppStrings.orderDetails: "Order Details",
      AppStrings.ongoingOrders: "Ongoing Orders",
      AppStrings.deliveryHistory: "Delivery History",
      AppStrings.searchOrderHint: "Search by date, status...",
      AppStrings.orderNo: "Order",
      AppStrings.deliveryDate: "Delivery",
      AppStrings.etaLabel: "ETA: Today, 5:30 PM",
      AppStrings.orderIdLabel: "Order ID:",
      AppStrings.expectedBy: "Expected By:",
      AppStrings.deliveryAddress: "Delivery Address",
      AppStrings.deliveryInformation: "Delivery Information",
      AppStrings.courierName: "Courier Name",
      AppStrings.stepOrder: "Order",
      AppStrings.stepPreparing: "Preparing",
      AppStrings.stepInDelivery: "In Delivery",
      AppStrings.stepDelivered: "Delivered",
      AppStrings.orderStatus: "Order Status",
      AppStrings.contactPharmacy: "Contact Pharmacy",
      AppStrings.reportAnIssue: "Report an issue",
      AppStrings.centralPharmacy: "Central Pharmacy",
      AppStrings.stepReady: "Ready",
      AppStrings.stepPickup: "Pick up",
      AppStrings.pickupAddress: "Pick up Address",
      AppStrings.reportIssue: "Report Issue",
      AppStrings.issueLabel: "Issue",
      AppStrings.issueHint: "Parcel Cancellation",
      AppStrings.descriptionLabel: "Description",
      AppStrings.reportDescriptionHint: "My parcel is cancelled without my permission",
      AppStrings.contactDriver: "Contact Driver",
      AppStrings.appointmentDetails: "Appointment Details",
      AppStrings.confirmed: "Confirmed",
      AppStrings.joinConsultation: "Join Consultation",
      AppStrings.reschedule: "Reschedule",
      AppStrings.medicalNotesDemo: "Hypertension follow-up. Blood pressure stable, continue medication",
      AppStrings.upcoming: "Upcoming",
      AppStrings.past: "Past",
      AppStrings.paymentOption: "Payment Option",
      AppStrings.confirmAndPay: "Confirm & Pay",
      AppStrings.warning: "Warning",
      AppStrings.onlyHomeVisit: "Only For Home Visit",
    },
    'fr_FR': {
      AppStrings.langSupport: "Support Linguistique",
      AppStrings.langDescription: "Assurer l'accessibilité et la convivialité de l'application dans plusieurs langues.",
      AppStrings.language: "Langue",
      AppStrings.cancel: "Annuler",
      AppStrings.confirm: "Confirmer",
      AppStrings.french: "Français",
      AppStrings.english: "Anglais",
      AppStrings.basicInfo: "Informations de base",
      AppStrings.fullName: "Nom complet",
      AppStrings.registrationId: "ID d'enregistrement",
      AppStrings.phoneNumber: "Numéro de téléphone",
      AppStrings.pharmacyAddress: "Adresse de la pharmacie",
      AppStrings.city: "Ville",
      AppStrings.areaLocality: "Zone / Localité",
      AppStrings.continueText: "Continuer",
      AppStrings.completeProfile: "Complétez votre profil",
      AppStrings.dob: "Date de naissance",
      AppStrings.email: "E-mail",
      AppStrings.gender: "Genre",
      AppStrings.countryResidence: "Pays de résidence",
      AppStrings.religion: "Religion",
      AppStrings.department: "Département",
      AppStrings.address: "Adresse",
      AppStrings.demographicInfo: "Informations démographiques",
      AppStrings.idNumber: "Numéro d'identification",
      AppStrings.clinicAddress: "Adresse de la clinique",
      AppStrings.aboutMe: "À propos de moi",
      AppStrings.aboutMeHint: "Écrivez quelque chose sur vous",
      AppStrings.docsAndReports: "Documents et rapports",
      AppStrings.uploadLabel: "Télécharger un document/rapport de test",
      AppStrings.uploadFormat: "Télécharger PDF/JPEG",
      AppStrings.tapToSelectNew: "Appuyez pour sélectionner un nouveau fichier",
      AppStrings.submit: "Soumettre",
      AppStrings.skip: "Passer",
      AppStrings.forgotPassword: "Mot de passe oublié ?",
      AppStrings.forgotPasswordSub: "Ensuite, soumettons la réinitialisation du mot de passe.",
      AppStrings.verifyEmail: "Vérification par e-mail",
      AppStrings.verifyEmailSub: "Vérifier le code par e-mail.",
      AppStrings.verifyWhatsapp: "Vérification via Whatsapp",
      AppStrings.verifyWhatsappSub: "Vérifier le code via Whatsapp.",
      AppStrings.codeSentEmail: "Un code à 6 chiffres a été envoyé par e-mail",
      AppStrings.codeSentWhatsapp: "Un code à 6 chiffres a été envoyé sur Whatsapp",
      AppStrings.medicalVitals: "Signes Vitaux",
      AppStrings.height: "Taille",
      AppStrings.weight: "Poids",
      AppStrings.bmi: "IMC",
      AppStrings.bloodPressure: "Tension Artérielle",
      AppStrings.heartRate: "Fréquence Cardiaque",
      AppStrings.professionalInfo: "Informations professionnelles",
      AppStrings.licenseNumber: "Numéro de licence",
      AppStrings.issuingAuthority: "Autorité de délivrance",
      AppStrings.issueDate: "Date d'émission",
      AppStrings.expiryDate: "Date d'expiration",
      AppStrings.businessRegNo: "N° d'enregistrement de l'entreprise",
      AppStrings.registeredName: "Nom enregistré",
      AppStrings.uploadInstruction: "Téléchargez des documents valides et clairs pour vérification. Seuls les formats PDF/JPEG sont acceptés.",
      AppStrings.licenseCertificate: "Certificat de licence",
      AppStrings.uploadLicense: "Téléchargez votre certificat de licence",
      AppStrings.acceptedFilesInfo: "Fichiers acceptés : PDF, JPEG – max 5 Mo.",
      AppStrings.taxClearance: "Quittance fiscale",
      AppStrings.uploadTax: "Télécharger la quittance fiscale",
      AppStrings.nocCertificate: "Certificat NOC",
      AppStrings.uploadNoc: "Téléchargez votre certificat NOC",
      AppStrings.payment: "Paiement",
      AppStrings.bankVerificationLetter: "Lettre de vérification bancaire",
      AppStrings.uploadBankConfirmation: "Télécharger la confirmation bancaire",
      AppStrings.paymentAuthorization: "Autorisation de paiement",
      AppStrings.attachSignedForm: "Joindre le formulaire signé",
      AppStrings.nationalIdDoc: "Document d'identité national",
      AppStrings.medicalSpeciality: "Spécialité médicale",
      AppStrings.experienceYears: "Expérience (en années)",
      AppStrings.fee: "Honoraires",
      AppStrings.dateOfRegistration: "Date d'enregistrement",
      AppStrings.placeOfPractice: "Lieu d'exercice",
      AppStrings.year: "Année",
      AppStrings.resetPassword: "Réinitialiser le mot de passe",
      AppStrings.resetPasswordSub: "Accédez à votre compte médical sécurisé",
      AppStrings.newPassword: "Nouveau mot de passe",
      AppStrings.enterPasswordHint: "Entrez votre mot de passe",
      AppStrings.confirmPassword: "Confirmez le mot de passe",
      AppStrings.reviewAndSubmission: "Révision et soumission",
      AppStrings.personalInfo: "Informations personnelles",
      AppStrings.supportingDocuments: "Documents justificatifs",
      AppStrings.consentDataProcessing: "Je consens au traitement de mes données personnelles",
      AppStrings.submissionConsentDetails: "En soumettant, vous consentez au traitement de vos données à des fins de vérification professionnelle. Vos informations sont traitées en toute sécurité selon les normes RGPD et HDS.",
      AppStrings.submitForVerification: "Soumettre pour vérification",
      AppStrings.signIn: "Se connecter",
      AppStrings.password: "Mot de passe",
      AppStrings.forgetPasswordTitle: "Mot de passe oublié",
      AppStrings.dontHaveAccount: "Vous n'avez pas de compte ?",
      AppStrings.signUp: "S'inscrire",
      AppStrings.createAccountSub: "Créez votre compte médical sécurisé",
      AppStrings.iAmDoctor: "Vous êtes médecin",
      AppStrings.iAmPatient: "Vous êtes un patient",
      AppStrings.iAmPharmacist: "Vous êtes pharmacien",
      AppStrings.alreadyHaveAccount: "Vous avez déjà un compte ?",
      AppStrings.identityDocuments: "Documents d'identité",
      AppStrings.uploadDocument: "Téléchargez votre document",
      AppStrings.passportIdFront: "Passeport ou recto de la carte d'identité",
      AppStrings.uploadFrontSide: "Télécharger le recto",
      AppStrings.credentials: "Références",
      AppStrings.medicalLicense: "Licence médicale",
      AppStrings.uploadValidLicense: "Téléchargez votre licence valide",
      AppStrings.diplomaCertification: "Diplôme / Certification",
      AppStrings.uploadDiplomaTranscript: "Télécharger le diplôme ou le relevé de notes",
      AppStrings.legal: "Juridique",
      AppStrings.liabilityInsuranceProof: "Preuve d'assurance responsabilité civile",
      AppStrings.uploadInsuranceDoc: "Télécharger le document d'assurance",
      AppStrings.cnpdGdprForm: "Formulaire CNPD / RGPD",
      AppStrings.attachComplianceForm: "Joindre le formulaire de conformité",
      AppStrings.twoFactorAuth: "Authentification à\n deux facteurs",
      AppStrings.twoFactorSub: "Ensuite, soumettons la réinitialisation du mot de passe.",
      AppStrings.verifyViaEmail: "Vérification par e-mail",
      AppStrings.emailCodeSent: "Un code à 6 chiffres a été envoyé par e-mail",
      AppStrings.verifyViaWhatsapp: "Vérification via Whatsapp",
      AppStrings.whatsappCodeSent: "Un code à 6 chiffres a été envoyé sur Whatsapp",
      AppStrings.back: "Retour",
      AppStrings.verification: "Vérification",
      AppStrings.requestNewCode: "Vous pouvez demander un nouveau code maintenant.",
      AppStrings.codeExpiresSoon: "Le code expire bientôt.",
      AppStrings.resendToWhatsapp: "Renvoyer sur Whatsapp",
      AppStrings.incompleteCode: "Code incomplet",
      AppStrings.incompleteCodeMsg: "Veuillez saisir le code de vérification complet à 6 chiffres.",
      AppStrings.hello: "Bonjour,",
      AppStrings.tomorrowAt: "Demain à",
      AppStrings.ongoingAppointment: "Rendez-vous en cours",
      AppStrings.upcomingAppointment: "Rendez-vous à venir",
      AppStrings.appointments: "Rendez-vous",
      AppStrings.prescription: "Ordonnance",
      AppStrings.orders: "Commandes",
      AppStrings.heartSurgeon: "Chirurgien cardiaque",
      AppStrings.gastroenterologist: "Gastro-entérologue",
      AppStrings.remoteConsultation: "Consultation à distance",
      AppStrings.join: "Rejoindre",
      AppStrings.sunday: "Dimanche",
      AppStrings.june: "Juin",
      AppStrings.currentOrder: "Commande actuelle",
      AppStrings.trackOrder: "Suivi de commande",
      AppStrings.detail: "Détail",
      AppStrings.packageId: "ID du colis",
      AppStrings.from: "De",
      AppStrings.estimated: "Estimation",
      AppStrings.mint: "min",
      AppStrings.orderStep: "Commande",
      AppStrings.preparingStep: "Préparation",
      AppStrings.inDeliveryStep: "En livraison",
      AppStrings.deliveredStep: "Livré",
      AppStrings.nextActions: "Actions suivantes",
      AppStrings.uploadPrescription: "Charger l'ordonnance",
      AppStrings.dosage: "Posologie",
      AppStrings.morningEvening: "Matin/Soir",
      AppStrings.refill: "Renouvellement",
      AppStrings.notifications: "Notifications",
      AppStrings.newCount: "Nouveau",
      AppStrings.markAllRead: "Tout marquer comme lu",
      AppStrings.today: "Aujourd'hui",
      AppStrings.yesterday: "Hier",
      AppStrings.chat: "Chat",
      AppStrings.search: "Rechercher",
      AppStrings.chatDescription: "Communiquez ici avec votre praticien pour toute question concernant votre traitement ou vos examens",
      AppStrings.noDataFound: "Aucune donnée trouvée",
      AppStrings.online: "En ligne",
      AppStrings.typeAMessage: "Message",
      AppStrings.searchHint: "Rechercher",
      AppStrings.findDoctorSub: "Trouvons un médecin qui vous convient",
      AppStrings.doctorsFound: "médecins trouvés",
      AppStrings.date: "Date",
      AppStrings.selectDate: "Choisir une date",
      AppStrings.location: "Emplacement",
      AppStrings.consultationMode: "Mode de consultation",
      AppStrings.inPerson: "En personne",
      AppStrings.teleconsultation: "Téléconsultation",
      AppStrings.distance: "Distance",
      AppStrings.male: "Masculin",
      AppStrings.female: "Féminin",
      AppStrings.price: "Prix",
      AppStrings.reset: "Réinitialiser",
      AppStrings.apply: "Appliquer",
      AppStrings.profile: "Profil",
      AppStrings.profileSub: "Messagerie en temps réel pour les consultations.",
      AppStrings.documentsAndReports: "Documents et rapports",
      AppStrings.deleteAccount: "Supprimer le compte",
      AppStrings.lastUpdate: "Dernière mise à jour",
      AppStrings.editPersonalInfo: "Modifier les infos personnelles",
      AppStrings.patientId: "ID Patient",
      AppStrings.countryOfResidence: "Pays de résidence",
      AppStrings.phone: "Téléphone",
      AppStrings.healthSpace: "Espace Santé",
      AppStrings.allergies: "Allergies",
      AppStrings.medicalHistory: "Historique médical",
      AppStrings.updatePassword: "Mettre à jour le mot de passe",
      AppStrings.bloodType: "Groupe sanguin",
      AppStrings.privacySecurity: "Confidentialité et sécurité",
      AppStrings.changeLanguage: "Changer de langue",
      AppStrings.consultationPlan: "Plan de consultation",
      AppStrings.logOut: "Se déconnecter",
      AppStrings.editMedicalVitals: "Modifier les signes vitaux",
      AppStrings.uploadNow: "Télécharger maintenant",
      AppStrings.viewing: "Visualisation de",
      AppStrings.deleting: "Suppression de",
      AppStrings.action: "Action",
      AppStrings.helpCenter: "Centre d'aide",
      AppStrings.faqs: "FAQ",
      AppStrings.faqQuestion1: "1. Les certificats sont-ils reconnus à l'international ?",
      AppStrings.faqQuestion2: "2. Dois-je renouveler mon adhésion manuellement ?",
      AppStrings.faqQuestion3: "3. Est-ce que je reçois des crédits FMC avec tous les forfaits ?",
      AppStrings.emailAddress: "Adresse e-mail",
      AppStrings.update: "Mettre à jour",
      AppStrings.addAllergy: "Ajouter une allergie",
      AppStrings.medical: "Médical",
      AppStrings.allergenName: "Nom de l'allergène",
      AppStrings.penicillin: "Pénicilline",
      AppStrings.reaction: "Réaction",
      AppStrings.rash: "Éruption cutanée",
      AppStrings.severity: "Gravité",
      AppStrings.dateIdentified: "Date identifiée",
      AppStrings.note: "Note",
      AppStrings.writeNoteHint: "Écrivez une note à votre médecin",
      AppStrings.save: "Enregistrer",
      AppStrings.currentMedication: "Médicament actuel",
      AppStrings.vaccinationHistory: "Historique des vaccinations",
      AppStrings.familyHistory: "Antécédents familiaux",
      AppStrings.lifestyle: "Mode de vie",
      AppStrings.addMedication: "Ajouter un médicament",
      AppStrings.addVaccinationHistory: "Ajouter une vaccination",
      AppStrings.addFamilyHistory: "Ajouter des antécédents familiaux",
      AppStrings.addLifeStyle: "Ajouter un mode de vie",
      AppStrings.oldPassword: "Ancien mot de passe",
      AppStrings.atLeast8Chars: "Au moins 8 caractères",
      AppStrings.atLeastOneUpper: "Au moins une lettre majuscule, ex: X, Y, Z",
      AppStrings.atLeastOneNumber: "Au moins un chiffre, ex: 1, 2, 3",
      AppStrings.atLeastOneSpecial: "Au moins un caractère spécial, ex: @, !, \$",
      AppStrings.passwordNotMatch: "Les mots de passe ne correspondent pas.",
      AppStrings.currentBloodType: "Groupe sanguin actuel",
      AppStrings.lastConfirmed: "Dernière confirmation",
      AppStrings.source: "Source",
      AppStrings.verificationStatus: "Statut de vérification",
      AppStrings.jan2024: "Janv 2024",
      AppStrings.medicalTestReport: "Rapport de test médical",
      AppStrings.verified: "Vérifié",
      AppStrings.updateBloodType: "Mettre à jour le groupe sanguin",
      AppStrings.editBloodType: "Modifier le groupe sanguin",
      AppStrings.uploadTestProof: "Télécharger la preuve du test",
      AppStrings.uploadProofOptional: "Télécharger la preuve du test (facultatif)",
      AppStrings.dataSharingPrefs: "Préférences de partage de données",
      AppStrings.dataSharingControl: "Contrôlez comment vos données médicales sont partagées et utilisées",
      AppStrings.dataProtected: "Vos données sont protégées",
      AppStrings.allowSharingHealthcare: "Autoriser le partage avec d'autres professionnels de santé",
      AppStrings.allowSharingSubtitle: "Partagez l'historique pour des soins coordonnés",
      AppStrings.allowResearchData: "Données anonymisées pour la recherche",
      AppStrings.allowResearchSubtitle: "Utilisé uniquement pour des analyses agrégées",
      AppStrings.receiveDataNotifications: "Notifications liées aux données",
      AppStrings.receiveNotificationsSubtitle: "Alertes d'accès ou de partage",
      AppStrings.whoCanAccessData: "Qui peut accéder à mes données ?",
      AppStrings.specialist: "Spécialistes",
      AppStrings.specialistSubtitle: "Peuvent voir après votre autorisation",
      AppStrings.emergencyServices: "Services d'urgence",
      AppStrings.emergencySubtitle: "Accès temporaire de 30 jours possible",
      AppStrings.pharmacy: "Pharmacie",
      AppStrings.pharmacySubtitle: "Uniquement pour ordonnances ou tests",
      AppStrings.alwaysAccessDefault: "Accès par défaut",
      AppStrings.accessHistory: "Historique des accès",
      AppStrings.trackHistorySubtitle: "Suivez qui a consulté vos dossiers",
      AppStrings.name: "Nom",
      AppStrings.role: "Rôle",
      AppStrings.data: "Données",
      AppStrings.dateTime: "Date et heure",
      AppStrings.exportMyData: "Exporter mes données",
      AppStrings.pdf: "PDF",
      AppStrings.selectDataType: "Type de données",
      AppStrings.dataController: "Responsable du traitement",
      AppStrings.dpoContact: "Contact DPO",
      AppStrings.hosting: "Hébergement :",
      AppStrings.gdprCompliance: "Conforme aux normes RGPD, CNPD et HDS.",
      AppStrings.myConsultationPlans: "Mes plans de consultation",
      AppStrings.activePlan: "Plan actif(2)",
      AppStrings.planHistory: "Historique du plan",
      AppStrings.searchConsultationHint: "Recherche par date, statut...",
      AppStrings.noOrdersFound: "Aucune commande trouvée.",
      AppStrings.consultationPlanDetail: "Détails du plan de consultation",
      AppStrings.planInfo: "Infos sur le plan",
      AppStrings.renewPlan: "Renouveler le plan",
      AppStrings.downloadInvoice: "Télécharger la facture",
      AppStrings.premiumTelePlan: "Plan de télé-consultation\nPremium",
      AppStrings.active: "Actif",
      AppStrings.videoConsultation: "Consultation vidéo",
      AppStrings.expiresOn: "Expire le",
      AppStrings.durationDays: "Durée : @days jours",
      AppStrings.credits: "@count crédits",
      AppStrings.description: "Description",
      AppStrings.planDescriptionText: "Amélioration des symptômes, fréquence des maux de tête réduite de 5 à 2 fois par semaine.",
      AppStrings.usageLog: "Journal d'utilisation",
      AppStrings.usageLogSubtitle: "Suivez qui a consulté ou modifié vos dossiers",
      AppStrings.consultationDate: "Date de consultation",
      AppStrings.type: "Type",
      AppStrings.doctor: "Docteur",
      AppStrings.status: "Statut",
      AppStrings.completed: "TERMINÉ",
      AppStrings.missed: "Manqué",
      AppStrings.deleteAccountWarning: "Cette action supprimera définitivement vos données médicales et votre profil, conformément au RGPD",
      AppStrings.autoDataDownload: "Téléchargement automatique des données avant suppression",
      AppStrings.relationLabel: "Relation @relation",
      AppStrings.diabetes: "Diabète",
      AppStrings.ageLabel: "Âge : @age ans",
      AppStrings.severityLabel: "Sévérité : @severity",
      AppStrings.mild: "Léger",
      AppStrings.antibioticWarning: "Éviter les antibiotiques de la même famille",
      AppStrings.lastUpdated: "Dernière mise à jour : @date",
      AppStrings.editAllergy: "Modifier l'allergie",
      AppStrings.allergyStatus: "Statut de l'allergie",
      AppStrings.uploadDocPhoto: "Télécharger Document/Photo",
      AppStrings.uploadPdfJpeg: "Télécharger PDF/JPEG",
      AppStrings.tapToSelectNewFile: "Appuyez pour sélectionner un nouveau fichier",
      AppStrings.noFileSelected: "Aucun fichier sélectionné",
      AppStrings.selectionCancelled: "Sélection de fichier annulée",
      AppStrings.writeNoteToDoctor: "Écrire une note à votre médecin",
      AppStrings.addVaccination: "Ajouter une vaccination",
      AppStrings.vaccinationName: "Nom du vaccin",
      AppStrings.influenza: "Grippe",
      AppStrings.uploadCertificate: "Télécharger le certificat",
      AppStrings.uploadLabReportHint: "Télécharger test de labo ou rapport (PDF, JPG, PNG)",
      AppStrings.addAndSave: "Ajouter et enregistrer",
      AppStrings.medicationName: "Nom du médicament",
      AppStrings.metforminHint: "Metformine 500mg",
      AppStrings.dosageHint: "1 comprimé deux fois par jour",
      AppStrings.doctorHint: "Dr. Maria Waston",
      AppStrings.addLifestyle: "Ajouter un mode de vie",
      AppStrings.smoking: "Tabagisme",
      AppStrings.alcohol: "Alcool",
      AppStrings.diet: "Régime alimentaire",
      AppStrings.physicalActivity: "Activité physique",
      AppStrings.relation: "Relation",
      AppStrings.condition: "Condition",
      AppStrings.hypertension: "Hypertension",
      AppStrings.age: "Âge",
      AppStrings.ageHint: "20",
      AppStrings.consultationFinished: "Consultation terminée",
      AppStrings.thankYouDoctor: "Merci d'avoir consulté @name",
      AppStrings.visitRatingTitle: "Comment évaluez-vous cette\nvisite ?",
      AppStrings.feedbackHint: "Parlez-nous de votre expérience......",
      AppStrings.viewPrescription: "Voir l'ordonnance",
      AppStrings.send: "Envoyer",
      AppStrings.preview: "Aperçu",
      AppStrings.encryptedCallNote: "Appel crypté de bout en bout.",
      AppStrings.launchVideo: "Lancer la vidéo",
      AppStrings.settings: "Paramètres",
      AppStrings.lastTested: "Dernier test : il y a @time",
      AppStrings.minutesAgo: "minutes",
      AppStrings.saveSettings: "Enregistrer les paramètres",
      AppStrings.restoreDefaults: "Restaurer les valeurs par défaut",
      AppStrings.doctorNotes: "Notes du docteur",
      AppStrings.addPrescription: "Ajouter une ordonnance",
      AppStrings.recentProjects: "Projets récents",
      AppStrings.endCall: "Fin d'appel",
      AppStrings.end: "Fin",
      AppStrings.inVideoMessages: "Messages vidéo",
      AppStrings.share: "Partager",
      AppStrings.captionsOff: "Sous-titres désactivés",
      AppStrings.addDoctorNote: "Ajouter une note médicale",
      AppStrings.addPrescriptionMenu: "Ajouter une ordonnance",
      AppStrings.viewReports: "Voir les rapports",
      AppStrings.patientHistory: "Historique du patient",
      AppStrings.observationsSubtitle: "Enregistrer les observations clés au cours de cette consultation",
      AppStrings.addNote: "Ajouter une note",
      AppStrings.noteHint: "Rédiger les observations pendant la consultation",
      AppStrings.noteSave: "Enregistrer la note",
      AppStrings.patientName: "Nom du patient",
      AppStrings.patientNameHint: "M. John",
      AppStrings.medicines: "Médicaments",
      AppStrings.medicinesHint: "Entrer les médicaments",
      AppStrings.refillDate: "Date de renouvellement",
      AppStrings.dateHint: "Entrer la date",
      AppStrings.prescriptionNotesHint: "Éviter les antibiotiques de la même famille",
      AppStrings.sendToPatient: "Envoyer au patient",
      AppStrings.uploadNewReport: "Télécharger un nouveau rapport",
      AppStrings.bloodTest: "Bilan sanguin",
      AppStrings.chestXray: "Radiographie pulmonaire",
      AppStrings.jan2025: "Janv 2025",
      AppStrings.endingCall: "Mettre fin à l'appel",
      AppStrings.endCallForBoth: "Mettre fin à l'appel pour les deux participants ?",
      AppStrings.anonymousFeedbackNote: "Vos commentaires sont anonymes et aident à améliorer la qualité du service",
      AppStrings.addNewCard: "Ajouter une carte",
      AppStrings.cardHolderName: "Nom du titulaire",
      AppStrings.enterName: "Entrez le nom",
      AppStrings.cardNumber: "Numéro de carte",
      AppStrings.saveDetail: "Enregistrer les détails",
      AppStrings.bookAppointment: "Prendre RDV",
      AppStrings.section: "Section",
      AppStrings.details: "Détails",
      AppStrings.confirmation: "Confirmation",
      AppStrings.remote: "À distance",
      AppStrings.homeVisit: "À domicile",
      AppStrings.availableTimes: "Horaires disponibles",
      AppStrings.homeVisitAlert: "Ce service n'est disponible que pour les praticiens\nproposant des visites à domicile.",
      AppStrings.confirmAppointment: "Confirmer le rendez-vous",
      AppStrings.submitRequest: "Envoyer la demande",
      AppStrings.cardHolderLabel: "TITULAIRE",
      AppStrings.myAppointment: "Mon rendez-vous",
      AppStrings.consultationDuration: "Consultation d'une heure",
      AppStrings.appointmentSummary: "Résumé du rendez-vous",
      AppStrings.next: "Suivant",
      AppStrings.doctorDetails: "Détails du Docteur",
      AppStrings.showNumber: "Afficher le numéro",
      AppStrings.patients: "patients",
      AppStrings.experience: "expérience",
      AppStrings.rating: "note",
      AppStrings.reviews: "avis",
      AppStrings.years: "ans",
      AppStrings.orderSummary: "Résumé",
      AppStrings.priceFor: "Prix pour",
      AppStrings.deliveryCharges: "Frais de livraison",
      AppStrings.homeDeliveryNote: "si livraison à domicile",
      AppStrings.totalFee: "Frais totaux",
      AppStrings.estimatedDeliveryTime: "Délai de livraison estimé",
      AppStrings.expectedDeliveryDays: "Prévu sous 2 à 3 jours ouvrables",
      AppStrings.certificationNote: "Pharmacie agréée — Certifiée par la CNPD et le ministère de la Santé",
      AppStrings.confirmOrder: "Confirmer la commande",
      AppStrings.prescriptionReceived: "Ordonnance reçue",
      AppStrings.prescriptionAvailableNote: "Votre ordonnance est disponible",
      AppStrings.modify: "Modifier",
      AppStrings.prescriptionDetails: "Détails de l'ordonnance",
      AppStrings.expirySoon: "Expire bientôt",
      AppStrings.expired: "Expirée",
      AppStrings.prescriptionInfo: "Infos ordonnance",
      AppStrings.dateOfIssue: "Date d'émission",
      AppStrings.validUntil: "Valable jusqu'au",
      AppStrings.eligibleTill: "Éligible jusqu'au :",
      AppStrings.nextDays: "Prochains @days jours",
      AppStrings.diagnosisHistory: "Historique du diagnostic",
      AppStrings.diagnosis: "Diagnostic",
      AppStrings.notes: "Notes",
      AppStrings.prescriptionHistory: "Historique des prescriptions",
      AppStrings.prescriptions: "Prescriptions",
      AppStrings.privacyNote: "Chiffré et conforme RGPD/HDS",
      AppStrings.electronicSign: "Signature électronique",
      AppStrings.digitalSignNote: "Cette ordonnance numérique est générée et signée par un praticien vérifié",
      AppStrings.getMedicine: "Acheter médicaments",
      AppStrings.downloadPdf: "Télécharger PDF",
      AppStrings.encryptionNote: "Crypté et conforme RGPD/HDS",
      AppStrings.activePrescriptions: "Ordonnances Actives",
      AppStrings.pastPrescriptions: "Ordonnances Passées",
      AppStrings.refillStatus: "État du renouvellement",
      AppStrings.approved: "Approuvé",
      AppStrings.noteLabel: "Note",
      AppStrings.noNotesAvailable: "Aucune note disponible",
      AppStrings.orderMedicine: "Commander des médicaments",
      AppStrings.requestRefill: "Demander un renouvellement",
      AppStrings.refillCycles: "Cycles de renouvellement",
      AppStrings.refillLabel: "Renouvellement",
      AppStrings.sendRequest: "Envoyer la demande",
      AppStrings.orderDetails: "Détails de la commande",
      AppStrings.ongoingOrders: "Commandes en cours",
      AppStrings.deliveryHistory: "Historique de livraison",
      AppStrings.searchOrderHint: "Rechercher par date, statut...",
      AppStrings.orderNo: "Commande",
      AppStrings.deliveryDate: "Livraison",
      AppStrings.etaLabel: "HPA: Aujourd'hui, 17h30",
      AppStrings.orderIdLabel: "ID commande:",
      AppStrings.expectedBy: "Prévu pour le:",
      AppStrings.deliveryAddress: "Adresse de livraison",
      AppStrings.deliveryInformation: "Informations de livraison",
      AppStrings.courierName: "Nom du coursier",
      AppStrings.stepOrder: "Commande",
      AppStrings.stepPreparing: "Préparation",
      AppStrings.stepInDelivery: "En livraison",
      AppStrings.stepDelivered: "Livré",
      AppStrings.orderStatus: "Statut de la commande",
      AppStrings.contactPharmacy: "Contacter la pharmacie",
      AppStrings.reportAnIssue: "Signaler un problème",
      AppStrings.centralPharmacy: "Pharmacie Centrale",
      AppStrings.stepReady: "Prêt",
      AppStrings.stepPickup: "Retrait",
      AppStrings.pickupAddress: "Adresse de retrait",
      AppStrings.reportIssue: "Signaler un problème",
      AppStrings.issueLabel: "Problème",
      AppStrings.issueHint: "Annulation de colis",
      AppStrings.descriptionLabel: "Description",
      AppStrings.reportDescriptionHint: "Mon colis est annulé sans ma permission",
      AppStrings.contactDriver: "Contacter le chauffeur",
      AppStrings.appointmentDetails: "Détails du rendez-vous",
      AppStrings.confirmed: "Confirmé",
      AppStrings.joinConsultation: "Rejoindre la consultation",
      AppStrings.reschedule: "Reporter",
      AppStrings.medicalNotesDemo: "Suivi d'hypertension. Tension artérielle stable, continuer les médicaments",
      AppStrings.upcoming: "À venir",
      AppStrings.past: "Passés",
      AppStrings.paymentOption: "Option de paiement",
      AppStrings.confirmAndPay: "Confirmer et payer",
      AppStrings.warning: "Avertissement",
      AppStrings.onlyHomeVisit: "Uniquement pour les visites à domicile",
    },
  };
}